extends:
  - eslint:recommended
  - airbnb

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  indent: [error, 2]
  quotes: [error, 'single']
  semi: [error, 'never']
  'no-console': [error]
  'max-len': [error, { code: 80 }]
