name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: make install

      - name: Install node packages
        run: yarn install

      - name: Run Rubocop and Slim lint
        run: make lint
      
      - name: Run test
        run: make test
